version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:5-alpine
    command: redis-server --port 6380
    env_file: .env
    ports:
      - "6380:6380"
    restart: always

  backend:
    container_name: backend
    build: ../backend
    command: >
      /bin/sh -c "poetry run python manage.py migrate --no-input
      && poetry run python manage.py collectstatic --no-input
      && poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/static/
      - uploaded_files:/app/uploaded_files/
      - ../backend/db.sqlite3:/app/db.sqlite3
    env_file: .env
    ports:
      - "8000:8000"
    restart: always

  celery:
    container_name: celery
    build: ../backend
    command: poetry run python -m celery -A config worker -l info
    volumes:
      - ../backend/db.sqlite3:/app/db.sqlite3
    env_file: .env
    depends_on:
      - redis
      - backend
    restart: always
  
  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static/
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static:
  uploaded_files:
